# Generated by Django 5.0.2 on 2024-02-23 14:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_remove_match_tournament_id_match_tournament_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
