# Generated by Django 5.0.2 on 2024-03-06 10:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_match_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
