# Generated by Django 5.0.2 on 2024-03-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_match_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='time_elapsed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='timer_started',
            field=models.BooleanField(default=False),
        ),
    ]
