# Generated by Django 5.0.2 on 2024-03-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0004_match_time_elapsed_match_timer_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='time_elapsed',
            field=models.IntegerField(default=120),
        ),
    ]
