# Generated by Django 5.0.2 on 2024-03-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0006_alter_match_time_elapsed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('joined', 'Joined'), ('playing', 'Playing'), ('completed', 'Completed')], default='pending', max_length=100),
        ),
    ]
