# Generated by Django 5.0.2 on 2024-03-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0007_alter_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='score_user_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='score_user_2',
            field=models.IntegerField(default=0),
        ),
    ]
