# Generated by Django 5.0.2 on 2024-03-15 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0006_tournament_status'),
        ('pong', '0008_match_score_user_1_match_score_user_2'),
    ]

    operations = [
    ]
