# Generated by Django 5.0.3 on 2024-03-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0009_merge_20240315_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(to='pong.participant'),
        ),
    ]
