# Generated by Django 5.0.3 on 2024-03-25 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0011_remove_tournament_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='matches_played',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('full', 'Full'), ('playing', 'Playing'), ('finished', 'Finished')], default='pending', max_length=100),
        ),
    ]
