# Generated by Django 5.0.3 on 2024-04-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0012_tournament_matches_played_alter_tournament_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='timer_started',
        ),
    ]
