# Generated by Django 5.0.3 on 2024-04-11 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0013_remove_match_timer_started'),
        ('pong', '0014_alter_match_tournament'),
    ]

    operations = [
    ]
