# Generated by Django 5.0.3 on 2024-04-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0015_merge_20240411_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('joined', 'Joined'), ('playing', 'Playing'), ('completed', 'Completed'), ('aborted', 'Aborted')], default='pending', max_length=100),
        ),
    ]
