# Generated by Django 5.0.3 on 2024-04-22 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0017_match_local_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='local_tournament',
        ),
    ]
