# Generated by Django 5.0.2 on 2024-03-11 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_blacklist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlackList',
        ),
    ]
