# Generated by Django 5.0.3 on 2024-03-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_blacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
