# Generated by Django 5.0.2 on 2024-03-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_otp_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_enabled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
