# Generated by Django 5.0.3 on 2024-03-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_otp_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
